version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm cache clean --force
      - npm install -g serverless
      - npm ci
      - npm install -g prisma
      - prisma generate
  build:
    commands:
      - echo Building application with serverless...
      - serverless package
  post_build:
    commands:
      - echo Updating Pronto API
      - aws lambda update-function-code --function-name $pronto_api_function_arn --s3-bucket $artifacts_bucket --s3-key $artifacts_key
      - echo Updating Pronto Reminder Service
      - aws lambda update-function-code --function-name $pronto_api_reminder_function_arn --s3-bucket $artifacts_bucket --s3-key $artifacts_key

artifacts:
  files:
    - "apollo-lambda.zip"
  base-directory: "./.serverless"
