version: "3.9"
services:
  db:
    image: "postgres:15.1"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: testpass11
      POSTGRES_DB: pronto
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
