service: apollo-lambda
provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:3000
  region: ${opt:region, 'us-east-1'}
functions:
  graphql:
    # Make sure your file path is correct!
    # (e.g., if your file is in the root folder use server.graphqlHandler )
    # The format is: <FILENAME>.<HANDLER>
    handler: src/index.handler # highlight-line
    events:
      - httpApi:
          path: /graphql/{any+}
          method: any
    role: arn:aws:iam::${aws:accountId}:role/write_eventbridge_events
    environment:
      reminderFunctionArn: arn:aws:lambda:${self:provider.region}:${aws:accountId}:function:${self:service}-${opt:stage, 'dev'}-reminderService
  reminderService:
    handler: src/services/reminder/index.handler # highlight-line
    events:
      - httpApi:
          path: /reminder/{any+}
          method: any
    role: arn:aws:iam::${aws:accountId}:role/read_eventbridge_events
# Omit the following lines if you aren't using TS!
plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000
  webpack:
    webpackConfig: ./webpack.config.js


